AWSTemplateFormatVersion: '2010-09-09'
Description: The template used to create an ECS Service from the ECS Console.
Parameters:
    ECSClusterName:
        Type: String
        Default: ProductionCluster
    ECSServiceName:
        Type: String
        Default: flaskApp
    SecurityGroupIDs:
        Type: CommaDelimitedList
        Default: sg-013654e802a455976
    SubnetIDs:
        Type: CommaDelimitedList
        Default: 'subnet-0b2cd7c034c205be6,subnet-05d37eeecf0310455,subnet-024ea0ea07964e9d9'
    VpcID:
        Type: String
        Default: vpc-0a61af4a16016581f
    LoadBalancerName:
        Type: String
        Default: ''
Resources:
    ECSService:
        Type: 'AWS::ECS::Service'
        Properties:
            Cluster: ProductionCluster
            CapacityProviderStrategy:
                - 
                    CapacityProvider: FARGATE
                    Base: 0
                    Weight: 1
            TaskDefinition: 'arn:aws:ecs:us-east-1:495599732171:task-definition/flashapptemplate:1'
            ServiceName: flaskApp
            SchedulingStrategy: REPLICA
            DesiredCount: 1
            AvailabilityZoneRebalancing: ENABLED
            NetworkConfiguration:
                AwsvpcConfiguration:
                    AssignPublicIp: ENABLED
                    SecurityGroups:
                        Ref: SecurityGroupIDs
                    Subnets:
                        Ref: SubnetIDs
            PlatformVersion: LATEST
            DeploymentConfiguration:
                DeploymentCircuitBreaker:
                    Enable: true
                    Rollback: true
                MaximumPercent: 200
                MinimumHealthyPercent: 100
            DeploymentController:
                Type: ECS
            ServiceConnectConfiguration:
                Enabled: false
            Tags: []
            EnableECSManagedTags: true
Outputs:
    ClusterName:
        Description: The cluster used to create the service.
        Value:
            Ref: ECSClusterName
    ECSService:
        Description: The created service.
        Value:
            Ref: ECSService
